### PR TITLE
adds constructor for disabling stdout buffering

### PR DESCRIPTION
**Pull request by dmalan**
@glennholloway, how does this strike you? I've named it `_init` for historical reasons, rather than introduce some new, arbitrary name? Cf. http://tldp.org/HOWTO/Program-Library-HOWTO/miscellaneous.html.

### CODE REVIEW

**Comment by crossroads1112** [comment]
libcs50 is a statically linked library so overriding _init does not work the same way as it does with dynamically linked libraries (since `dlopen` isn't called to load it). In fact, this does not build on my laptop because of conflicting definitions of `_init` (this one and the one defined in crti.o). Furthermore, the constructor attribute exists for the express purpose of **not** overriding the implementation's _init. Renaming the function to `init` or any other nonreserved name resolves this problem but there still are a major gotcha if libcs50 remains statically linked: 

* Because the library is statically linked, if a student writes a program and does not use one of the libcs50 functions, there will be no undefined symbols in the object file when the linker starts up meaning the constructor will not be included. This means that the following programs would behave differently:

    #include <stdio.h>
    #include <stdlib.h>
    #include <cs50.h> 
    int main(void)
    { 
        int (*f)(void) =  get_int; // Introduce get_int symbol
        printf("These will appear ");
        sleep(5);
        printf("at the same time\n");
    }

and

    #include <stdio.h>
    #include <stdlib.h>
    #include <cs50.h>
    int main(void)
    {
         printf("This will appear first, ");
        sleep(5);
        printf("then this\n");
    }

-------------

A more philosophical consideration would be that these constructors are often used to initialize data structures and such that are local to their own library, but this constructor makes a *global* change and affects functions entirely unrelated to libcs50. It seems a little strange that, say, `printf` would have different behavior just because libcs50 is linked.

Also, a slightly less verbose way to disable buffering is `setbuf(stdout, NULL)`

**Comment by kzidane** [comment]
I think @crossroads1112 has a point. 

 * doesn't compile due to multiple definitions of `_init`. changing name fixes it. 
 * constructor isn't included, if no reference in the program. however, in my case, it seems that constructor is included, even if only `cs50.h` is included (i.e., no functions from libcs50 are referenced)? in other words, @crossroads1112's sample programs behave the same, but if `#include <cs50.h>` is removed from the second program, behavior is different.
 * agree on the local initialization and the less verbose points.

just out of curiosity, @dmalan, why is this important?

**Comment by IvanJasenov** [comment]
When declaring the libraries, try to place cs50.h first. Order of execution
and declaration in compilers can sometimes cause a mess. Sorry, don't have
access to my laptop at this moment. :/

**Comment by crossroads1112** [comment]
@kzidane My fault! I was using an older version of the cs50 library (before the function pointers for GetChar et al. were added. Because they are declared in the header file, symbols from libcs50.a are being used. Still, as these function pointers are deprecated anyway, it seems like thin ice.

Follow up question: is there a reason libcs50 isn't dynamically linked? It would seem like it would make updating it easier.

**Comment by dmalan** [comment]
@kzidane:

* The addition of `static` to `_init` should address your first bullet now?
* Indeed, that's intentional at the moment.

@kzidane, @crossroads1112: The overarching goal is to disable buffering of `stdout`, particularly for less-comfortable students. In office hours, we often see situations where a student is trying to use `printf` to debug something, but their message isn't printing (because, e.g., they've omitted a `\n` and have an infinite loop below the call the `printf`). Or, because of a missing `\n`, their output appears seemingly later in their program's execution than they intend. While we then use such situations as opportunities to explain the symptom, that's usually only after all too much time and frustration, especially early in the term when a student reasonably expects that `printf` will indeed print.

We've considered addressing this by disabling `stdout` buffering in students' shells, as with `stdbuf`. But we're a bit reluctant to run all commands through `stdbuf`, lest there be unforeseen consequences. E.g., an earlier idea had us put

`stdbuf -i0 -o0 -e0 bash -l ; exit` in `/etc/profile.d/ide50.sh`, but the effect, of course, is to induce `bash` to spawn itself recursively (because `-l` compels `/etc/profile.d/*` to be sourced again). We contemplated coming up with a way to ensure that `stdbuf` is only called once (for the "parent" shell), but there too, we worry there might be unforeseen consequences. Alternatively, we could create a `bash50` shell that does what we want, but we worry that too might break something on C9, which assumes `ubuntu` has certain characteristics.

So that led us to consider `__attribute__((constructor))` so that `stdout` is indeed unbuffered whenever students use the CS50 Library, which would be toward the beginning of term, when this issue tends to crop up the most. A bit of magic, to be sure, but consistent with the CS50 Library being training wheels that we eventually take off anyway.

But changing our compilation process to make the library a shared library, with `-shared`, would seem to address the issue you cite, @crossroads1112.

Thoughts on other approaches altogether?

**Comment by crossroads1112** [comment]
Perhaps an exec50 function defined in ide50?

    function exec50 {
        if (( $# < 1 )); then
            printf "Please supply a command to be run\n"
            return 1
        fi
        eval "stdbuf -i0 -e0 -o0 -- $@"
    }

Or perhaps keep the constructor approach but at the very least make it contingent on an environment variable that is set in ide50.sh? That way once the libcs50 magic is revealed, the student could disable the nonstandard behavior if he/she wants

**Comment by dmalan** [comment]
@crossroads1112, whereby the student would have to run `exec50` explicitly to run their program? Not sure that gains us much, since a student who knows to run `exec50` as a solution could just `fflush` within their code (or add a `\n` i missing). And not sure we'd need the environment variable. By the time a student is comfortable disabling such behavior, odds are they wouldn't be using the CS50 Library anymore anyway!

**Comment by kzidane** [comment]
@crossroads1112 ah! totally forgot about the function pointers in `cs50.h`.

@dmalan makes sense. thanks for explaining! yes, `static` seems to have fixed the compilation problem. not sure if there's a better approach though. this seems to be exactly what you want? (i.e., disabling buffering on `stdout` as long as students are putting training wheels). perhaps different behaviors then are not that big of a concern then, since students won't experience them, as long as they're putting these training wheels?

agree on providing another printf is too much, and that `exec50` and env var are not the best ideas!

removing `static` and making libcs50 shared would solve the conflict issue as well, but 5.2.1 [here](http://tldp.org/HOWTO/Program-Library-HOWTO/miscellaneous.html) suggests that `_init` is obsolete and shouldn't be used?

**Comment by dmalan** [comment]
Rewritten!

**Pull request closed without merging**
