### PR TITLE
finishes implementation of eprintf

### PR DESCRIPTION
**Pull request by dmalan**
@glennholloway, @kzidane, spot any issues? Glenn, I moved `format` to precede immediately `...`, if only for consistency with `printf` and family.

### CODE REVIEW

**Comment by kzidane** [comment]
@dmalan only this #12?

**Comment by glennholloway** [comment]
@dmalan The comment before the `va_start` call is out of date. The last parameter before `...` is now the format string. The comment before the matching `va_end` call might better read something like `End traversal of ap`. The `ap` variable is still valid in the sense that another `va_start`/`va_end` pair could be used to traverse the variable arg list again.

**Comment by dmalan** [comment]
Not sure what you mean, @kzidane?

**Comment by dmalan** [comment]
Thanks, @glennholloway! fwiw, the `va_end` comment is actually based on the man page's, language:

> After a variable argument list is invalidated by `va_end()`, it can be reinitialized with va_start() or made a copy of another variable argument list with `va_copy()`.

**Pull request merged**
